import { useState } from 'react'
import { simulate, generateNodes } from '../services/api'
import SimulationChart from './SimulationChart'

function SimulationDashboard() {
    const SIM_MONTHS = 12
    const SIM_RUNS = 50
    const [sidebarOpen, setSidebarOpen] = useState(false)

    const [initialState, setInitialState] = useState({
        cash: 1000000,
        burn: 50000,
        revenue: 20000,
        cac: 100,
        customers: 500,
        arpu: 40,
        ltv: 1200,
        ad_spend: 10000,
        traffic: 10000,
        new_customers: 200,
        runway: 20,
        churn_rate: 0.05,
        month: 0
    })

    // Options generated by Gemini
    const [options, setOptions] = useState([])
    const [loadingOptions, setLoadingOptions] = useState(false)

    // Selected simulation
    const [selectedOption, setSelectedOption] = useState(null)

    // Simulation Results
    const [simulationResults, setSimulationResults] = useState(null)
    const [loadingSimulation, setLoadingSimulation] = useState(false)
    const [error, setError] = useState(null)

    const handleInputChange = (e) => {
        const { name, value } = e.target
        setInitialState(prev => ({
            ...prev,
            [name]: parseFloat(value) || 0
        }))
    }

    const handleGenerateOptions = async () => {
        setLoadingOptions(true)
        setError(null)
        setOptions([])
        try {
            const data = await generateNodes(initialState)

            // Transform nodes into a format suitable for selection
            // The API returns { nodes: [ { description, impact: {...} }, ... ] }
            if (data.nodes) {
                setOptions(data.nodes)
            }
        } catch (err) {
            setError(err.message)
        } finally {
            setLoadingOptions(false)
        }
    }


    const handleRunSimulation = async (option) => {
        setSelectedOption(option)
        setLoadingSimulation(true)
        setError(null)
        setSimulationResults(null)

        // Construct action object from option description (simplified)
        // The backend expects 'action' dict. We'll pass the whole option or a constructed one.
        // For now the backend simulation function takes 'action' dict but the logic is based on applying modifiers from Gemini.
        // Actually monte_carlo.py expects 'action' to update state, but `run_monte_carlo` uses the action to update state BEFORE running.
        // BUT our Gemini modifiers come from `third_order`.
        // Let's pass the option description as a "strategic_directive" if possible, or just empty action if we rely on the prompt.
        // Wait, `run_monte_carlo` takes `action`.
        // Let's assume the user selects an option which IMPLIES an action (e.g. "Increase ad spend").
        // The `generate_nodes` returned options with projected impacts.
        // For this demo, let's treat the option as a "modifier" context.
        // We'll pass `option` as the action context.

        try {
            // The backend simulator expects concrete parameter overrides (e.g. { ad_spend: 20000 }).
            // Gemini node generation returns these under `suggested_shifts`.
            const actionPayload = option?.suggested_shifts && typeof option.suggested_shifts === 'object'
                ? option.suggested_shifts
                : {}

            const results = await simulate(initialState, actionPayload, SIM_MONTHS, SIM_RUNS)

            // Transform results to look like a "Node" for NodeDetails
            const resultNode = {
                id: 'sim_result',
                strategy: option,
                description: option?.description || option?.name || 'Selected decision',
                meta: {
                    months: SIM_MONTHS,
                    num_runs: SIM_RUNS,
                    action_applied: actionPayload,
                },
                finance: {
                    summary: `Survival Probability: ${(results.survival_probability * 100).toFixed(1)}%`,
                    metrics: [
                        { name: 'Survival Probability', value: results.survival_probability * 100, unit: '%' },
                        { name: 'P50 Cash', value: results.p50, unit: '$' },
                        { name: 'P10 Cash', value: results.p10, unit: '$' },
                        { name: 'P90 Cash', value: results.p90, unit: '$' },
                    ],
                    recommendations: results.gemini_recommendations || [],
                    risks: results.gemini_risks || [],
                },
                research: {
                    confidence: results.survival_probability, // Proxy
                    summary: `Distribution summary across ${SIM_RUNS} Monte Carlo runs.`,
                    risks: results.gemini_risks,
                    opportunities: results.gemini_opportunities
                },
                traces: results.traces, // Pass full traces for the viewer
                series: results.series // Time-series for the graph
            }

            setSimulationResults(resultNode)

        } catch (err) {
            setError(err.message)
        } finally {
            setLoadingSimulation(false)
        }
    }

    return (
        <div className="flex h-screen bg-black text-zinc-300 font-sans overflow-hidden">
            {/* Left Sidebar: Controls & State */}
            <div className="md:hidden fixed top-0 left-0 right-0 z-20 flex items-center gap-3 px-4 py-3 border-b border-zinc-800 bg-zinc-950">
                <button
                    onClick={() => setSidebarOpen(true)}
                    className="text-zinc-300 text-lg"
                >
                    ☰
                </button>
                <span className="text-sm font-semibold text-white">
                    Business Simulator
                </span>
            </div>

            {/* Overlay */}
            {sidebarOpen && (
                <div
                    onClick={() => setSidebarOpen(false)}
                    className="fixed inset-0 bg-black/60 z-30 md:hidden"
                />
            )}

            {/* Sidebar */}
            <aside
                className={`
                    fixed z-40 inset-y-0 left-0 w-80
                    bg-zinc-950 border-r border-zinc-800 p-4 overflow-y-auto
                    transform transition-transform duration-300
                    ${sidebarOpen ? 'translate-x-0' : '-translate-x-full'}
                    md:static md:translate-x-0
                `}
            >
                <div className="md:hidden flex justify-end mb-2">
                    <button
                        onClick={() => setSidebarOpen(false)}
                        className="text-zinc-400 text-sm"
                    >
                        ✕
                    </button>
                </div>

                <h1 className="text-xl font-bold text-white mb-6 hidden md:block">
                    Business Simulator
                </h1>

                <h2 className="text-sm font-semibold text-zinc-500 mb-3 uppercase">
                    Current State
                </h2>

                <div className="space-y-3 mb-6">
                    {Object.entries(initialState).map(([key, value]) => (
                        <div key={key} className="flex flex-col">
                            <label className="text-[10px] uppercase text-zinc-600 mb-1">
                                {key.replace('_', ' ')}
                            </label>
                            <input
                                type="number"
                                name={key}
                                value={value}
                                onChange={handleInputChange}
                                className="bg-zinc-900 border border-zinc-800 rounded px-2 py-1 text-xs"
                            />
                        </div>
                    ))}
                </div>

                <button
                    onClick={handleGenerateOptions}
                    disabled={loadingOptions}
                    className="w-full bg-blue-600 hover:bg-blue-500 text-white rounded py-2 text-sm"
                >
                    {loadingOptions ? 'Generating...' : 'Generate Strategic Options'}
                </button>

                {error && (
                    <div className="mt-4 text-xs text-red-400">
                        {error}
                    </div>
                )}
            </aside>

            {/* Center: Options & Simulation */}
            <div className="flex-1 flex flex-col min-w-0 bg-black">
                <div className="p-6 overflow-y-auto flex-1">
                    {/* Strategic Options */}
                    {options.length > 0 && !simulationResults && !loadingSimulation && (
                        <div className="max-w-4xl mx-auto">
                            <h2 className="text-lg font-semibold text-white mb-4">Strategic Decisions</h2>
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                {options.map((option, idx) => (
                                    <div
                                        key={idx}
                                        onClick={() => handleRunSimulation(option)}
                                        className="cursor-pointer group rounded-xl border border-zinc-800 bg-zinc-900/50 p-4 hover:bg-zinc-900 hover:border-blue-500/50 transition-all"
                                    >
                                        <div className="flex justify-between items-start mb-2">
                                            <h3 className="font-medium text-zinc-200 group-hover:text-blue-400 transition-colors">
                                                {option.name || 'Decision'}
                                            </h3>
                                            <span className="text-xs bg-zinc-800 text-zinc-400 px-2 py-1 rounded">
                                                {(option.probability * 100).toFixed(0)}% prob
                                            </span>
                                        </div>
                                        <div className="space-y-2 mt-3">
                                            <p className="text-xs text-zinc-400 leading-relaxed line-clamp-3">
                                                {option.description}
                                            </p>
                                            {option.impact && (
                                                <p className="text-xs text-zinc-500 line-clamp-2">
                                                    Projected impact: {option.impact}
                                                </p>
                                            )}
                                            {option.suggested_shifts && (
                                                <p className="text-[11px] text-zinc-600 line-clamp-2">
                                                    Suggested shifts: {Object.entries(option.suggested_shifts)
                                                        .map(([k, v]) => `${k.replaceAll('_', ' ')} → ${v}`)
                                                        .join(', ')}
                                                </p>
                                            )}
                                        </div>
                                    </div>
                                ))}
                            </div>
                        </div>
                    )}

                    {/* Loading State */}
                    {loadingSimulation && (
                        <div className="flex flex-col items-center justify-center h-full">
                            <div className="h-8 w-8 text-blue-500 animate-spin mb-4">
                                <svg className="w-full h-full" fill="none" viewBox="0 0 24 24">
                                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                                </svg>
                            </div>
                            <p className="text-sm text-zinc-500">Running Monte Carlo Simulations...</p>
                        </div>
                    )}

                    {/* Results View */}
                    {simulationResults && (
                        <div className="max-w-5xl mx-auto">
                            <button
                                onClick={() => setSimulationResults(null)}
                                className="mb-6 text-xs text-zinc-500 hover:text-white flex items-center gap-1"
                            >
                                ← Back to Options
                            </button>

                            {/* Selected Decision + Simulation Parameters */}
                            <div className="mb-6 grid grid-cols-1 lg:grid-cols-3 gap-4">
                                {/* Selected Decision */}
                                <div className="lg:col-span-2 rounded-xl border border-zinc-800 bg-zinc-900/40 p-5">
                                    <div className="flex flex-col gap-3 md:flex-row md:items-start md:justify-between">
                                        <div className="min-w-0">
                                            <div className="text-[10px] uppercase tracking-wider text-zinc-500">
                                                Selected decision
                                            </div>
                                            <div className="mt-1 text-xl font-semibold text-white">
                                                {selectedOption?.name || 'Decision'}
                                            </div>
                                            {selectedOption?.description && (
                                                <p className="mt-2 text-sm leading-relaxed text-zinc-300">
                                                    {selectedOption.description}
                                                </p>
                                            )}
                                        </div>
                                        {typeof selectedOption?.probability === 'number' && (
                                            <div className="flex-shrink-0 rounded-lg bg-zinc-900 border border-zinc-800 px-3 py-2">
                                                <div className="text-[10px] uppercase tracking-wider text-zinc-500">Assumed probability</div>
                                                <div className="mt-0.5 font-mono text-sm text-zinc-200">
                                                    {(selectedOption.probability * 100).toFixed(0)}%
                                                </div>
                                            </div>
                                        )}
                                    </div>

                                    {selectedOption?.impact && (
                                        <div className="mt-4 rounded-lg border border-zinc-800 bg-zinc-950/40 p-3">
                                            <div className="text-[10px] uppercase tracking-wider text-zinc-500 mb-1">
                                                Impact (from generation)
                                            </div>
                                            <p className="text-xs leading-relaxed text-zinc-400">
                                                {selectedOption.impact}
                                            </p>
                                        </div>
                                    )}
                                </div>

                                {/* Simulation Parameters */}
                                <div className="rounded-xl border border-zinc-800 bg-zinc-900/40 p-5">
                                    <h3 className="text-sm font-medium text-blue-400 mb-3">
                                        Simulation Parameters
                                    </h3>
                                    <dl className="grid grid-cols-2 gap-x-4 gap-y-2 text-xs">
                                        <dt className="text-zinc-500">Initial Cash:</dt>
                                        <dd className="text-zinc-300 text-right">${initialState.cash.toLocaleString()}</dd>
                                        <dt className="text-zinc-500">Monthly Burn:</dt>
                                        <dd className="text-zinc-300 text-right">${initialState.burn.toLocaleString()}</dd>
                                        <dt className="text-zinc-500">Churn Rate:</dt>
                                        <dd className="text-zinc-300 text-right">{(initialState.churn_rate * 100).toFixed(1)}%</dd>
                                        <dt className="text-zinc-500">Runs:</dt>
                                        <dd className="text-zinc-300 text-right">{simulationResults.meta?.num_runs || SIM_RUNS}</dd>
                                        <dt className="text-zinc-500">Duration:</dt>
                                        <dd className="text-zinc-300 text-right">{simulationResults.meta?.months || SIM_MONTHS} Months</dd>
                                    </dl>

                                    {selectedOption?.suggested_shifts && Object.keys(selectedOption.suggested_shifts).length > 0 && (
                                        <div className="mt-4 pt-4 border-t border-zinc-800">
                                            <h4 className="text-xs text-zinc-500 uppercase mb-2">Applied shifts</h4>
                                            <ul className="text-xs space-y-1">
                                                {Object.entries(selectedOption.suggested_shifts).map(([k, v]) => (
                                                    <li key={k} className="flex items-center justify-between gap-3">
                                                        <span className="text-zinc-500">{k.replaceAll('_', ' ')}</span>
                                                        <span className="font-mono text-zinc-300">{String(v)}</span>
                                                    </li>
                                                ))}
                                            </ul>
                                        </div>
                                    )}
                                </div>
                            </div>

                            <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-6">
                                {simulationResults.finance.metrics.map((metric, idx) => (
                                    <div key={idx} className="bg-zinc-900 border border-zinc-800 p-4 rounded-lg">
                                        <div className="text-zinc-500 text-xs uppercase tracking-wider mb-1">{metric.name}</div>
                                        <div className="text-xl font-mono text-white">
                                            {metric.name.includes('Prob') ? '' : '$'}
                                            {metric.value.toLocaleString(undefined, { maximumFractionDigits: 0 })}
                                            {metric.unit === '%' ? '%' : ''}
                                        </div>
                                    </div>
                                ))}
                            </div>

                            <SimulationChart
                                data={simulationResults.series}
                                months={simulationResults.meta?.months || SIM_MONTHS}
                                numRuns={simulationResults.meta?.num_runs || SIM_RUNS}
                            />

                            {/* AI Strategic Analysis */}
                            <div className="bg-zinc-900/30 border border-zinc-800 rounded-lg p-5">
                                <h3 className="text-sm font-medium text-emerald-400 mb-3 flex items-center gap-2">
                                    🤖 AI Strategic Analysis
                                </h3>
                                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                                    <div>
                                        <h4 className="text-xs text-zinc-500 uppercase mb-2">Gemini Recommendations</h4>
                                        <ul className="text-sm text-zinc-300 space-y-1 list-disc pl-4">
                                            {simulationResults.finance.recommendations.length > 0 ? (
                                                simulationResults.finance.recommendations.map((rec, i) => <li key={i}>{rec}</li>)
                                            ) : (
                                                <li className="text-zinc-600 italic">No specific recommendations generated.</li>
                                            )}
                                        </ul>
                                    </div>
                                    <div>
                                        <h4 className="text-xs text-zinc-500 uppercase mb-2">Identified Risks</h4>
                                        <ul className="text-sm text-zinc-300 space-y-1 list-disc pl-4">
                                            {simulationResults.finance.risks.length > 0 ? (
                                                simulationResults.finance.risks.map((r, i) => <li key={i}>{r}</li>)
                                            ) : (
                                                <li className="text-zinc-600 italic">No specific risks flagged.</li>
                                            )}
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    )}

                    {/* Initial Empty State */}
                    {options.length === 0 && !loadingOptions && !simulationResults && (
                        <div className="flex flex-col items-center justify-center h-full text-zinc-600">
                            <div className="text-4xl mb-4">🚀</div>
                            <p>Configure the state on the left and generate options to begin.</p>
                        </div>
                    )}
                </div>
            </div>

            {/* Right Sidebar: Streaming/Logs (Optional, reused if we had streaming events) */}
            {/* We reuse StreamingPanel but currently we don't have a live stream of events from backend yet, 
            so we might just hide it or use it for static logs if we had them. 
            For now, let's omit or just show a placeholder. */}
        </div>
    )
}

export default SimulationDashboard
