import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer, ReferenceLine } from 'recharts';

function SimulationChart({ data, months = 12, numRuns = 50, failureThreshold = 0 }) {
    if (!data || data.length === 0) return (
        <div className="flex items-center justify-center h-64 bg-zinc-900/50 rounded-lg border border-zinc-800 text-zinc-500 text-xs">
            No chart data available
        </div>
    );

    return (
        <div className="w-full bg-zinc-900/30 rounded-lg border border-zinc-800 p-4 mb-4">
            <div className="mb-2">
                <h3 className="text-xs font-semibold text-zinc-400 uppercase tracking-wide">
                    Cash Flow Projection ({months} Months)
                </h3>
                <p className="mt-1 text-[11px] leading-relaxed text-zinc-500">
                    Generated by running {numRuns} Monte Carlo simulations forward {months} months (same Gemini-derived “third-order” modifiers, with small per-month random noise).
                    The lines show the P10/P50/P90 cash percentiles across runs each month; the summary metrics are percentiles of final cash, and survival is the % of runs ending with cash &gt; 0.
                </p>
            </div>
            <div className="h-56">
                <ResponsiveContainer width="100%" height="100%">
                    <LineChart
                        data={data}
                        margin={{ top: 5, right: 30, left: 20, bottom: 5 }}
                    >
                        <CartesianGrid strokeDasharray="3 3" stroke="#333" />
                        <XAxis
                            dataKey="month"
                            stroke="#666"
                            tick={{ fontSize: 10 }}
                            label={{ value: 'Month', position: 'insideBottomRight', offset: -5, fill: '#666', fontSize: 10 }}
                        />
                        <YAxis
                            stroke="#666"
                            tick={{ fontSize: 10 }}
                            tickFormatter={(value) => `$${value / 1000}k`}
                        />
                        <Tooltip
                            contentStyle={{ backgroundColor: '#18181b', borderColor: '#3f3f46', fontSize: '12px' }}
                            itemStyle={{ fontSize: '12px' }}
                            formatter={(value) => [`$${value.toLocaleString()}`, '']}
                        />
                        <Legend wrapperStyle={{ fontSize: '12px' }} />
                        <ReferenceLine y={failureThreshold} stroke="red" strokeDasharray="3 3" />

                        <Line
                            type="monotone"
                            dataKey="p90"
                            name="Upside (P90)"
                            stroke="#10b981"
                            strokeWidth={1}
                            dot={false}
                        />
                        <Line
                            type="monotone"
                            dataKey="p50"
                            name="Median (P50)"
                            stroke="#3b82f6"
                            strokeWidth={2}
                            activeDot={{ r: 4 }}
                        />
                        <Line
                            type="monotone"
                            dataKey="p10"
                            name="Downside (P10)"
                            stroke="#ef4444"
                            strokeWidth={1}
                            dot={false}
                        />
                    </LineChart>
                </ResponsiveContainer>
            </div>
        </div>
    );
}

export default SimulationChart;
